name: Bridge Example
plugins:
  - name: solidity
dependencies:
  - name: Connext
    github: connext/monorepo
    version: v0.2.1-rc.12
solidity:
  import_remapping:
    - "@connext=Connext/v0.2.1-rc.12/packages/deployments/contracts/contracts"
